-- Create the mcq_results table
CREATE TABLE IF NOT EXISTS mcq_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number text,
    name text,
    email text NOT NULL,
    college text,
    year text,
    department text,
    test_id text NOT NULL,
    test_name text,
    score integer DEFAULT 0,
    total_questions integer DEFAULT 0,
    correct_answers integer DEFAULT 0,
    incorrect_answers integer DEFAULT 0,
    percentage numeric DEFAULT 0, -- Store as decimal (e.g. 0.72 for 72%)
    time_taken integer DEFAULT 0, -- in seconds
    time_taken_formatted text,
    time_started text,
    time_ended text,
    submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    auto_submitted boolean DEFAULT false,
    auto_submit_reason text,
    violation_count integer DEFAULT 0,
    total_no_face integer DEFAULT 0,
    total_multiple_faces integer DEFAULT 0,
    violations jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add unique constraint on (email, test_id) to match the Firestore uniqueness
-- and allow clean upserting (only one submission record per student per test)
ALTER TABLE mcq_results ADD CONSTRAINT unique_email_test_id UNIQUE (email, test_id);

-- Add index on college for fast retrieval in StaffDashboard
CREATE INDEX IF NOT EXISTS idx_mcq_results_college ON mcq_results(college);

-- Create the coding_results table
CREATE TABLE IF NOT EXISTS coding_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number text,
    name text,
    email text NOT NULL,
    college text,
    year text,
    department text,
    test_id text NOT NULL,
    test_name text,
    score integer DEFAULT 0,
    total_questions integer DEFAULT 0,
    correct_answers integer DEFAULT 0,
    incorrect_answers integer DEFAULT 0,
    percentage numeric DEFAULT 0, -- Store as decimal (e.g. 0.72 for 72%)
    status text DEFAULT 'started', -- 'started', 'submitting', 'submitted'
    time_taken integer DEFAULT 0, -- in seconds
    time_taken_formatted text,
    time_started text,
    time_ended text,
    submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    auto_submitted boolean DEFAULT false,
    auto_submit_reason text,
    violation_count integer DEFAULT 0,
    violations jsonb DEFAULT '[]'::jsonb,
    code_map jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add unique constraint on (email, test_id)
ALTER TABLE coding_results ADD CONSTRAINT unique_coding_email_test_id UNIQUE (email, test_id);

-- Add index on college
CREATE INDEX IF NOT EXISTS idx_coding_results_college ON coding_results(college);

-- Create the ai_interview_results table
CREATE TABLE IF NOT EXISTS ai_interview_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number text,
    name text,
    email text NOT NULL,
    college text,
    year text,
    department text,
    domain text NOT NULL,
    difficulty text NOT NULL,
    company text NOT NULL,
    score_technical numeric DEFAULT 0,
    score_communication numeric DEFAULT 0,
    score_problem_solving numeric DEFAULT 0,
    score_confidence numeric DEFAULT 0,
    score_overall numeric DEFAULT 0,
    feedback jsonb DEFAULT '{}'::jsonb, -- Store strengths, weaknesses, tips, full conversation logs
    duration_seconds integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index on email and college for fast queries
CREATE INDEX IF NOT EXISTS idx_ai_interview_results_email ON ai_interview_results(email);
CREATE INDEX IF NOT EXISTS idx_ai_interview_results_college ON ai_interview_results(college);


